---
image:
    file: .gitpod.Dockerfile

tasks:
    - init: pip3 install --upgrade conan && pre-commit install -f --hook-type pre-commit
      command: rm -rf ./build && cmake -S . --preset=linux-debug-ninja-clang

vscode:
    extensions:
        - ms-vscode.cmake-tools
        - twxs.cmake
