---
image:
    file: .gitpod.Dockerfile

tasks:
    - before: |
          pre-commit install -f --hook-type pre-commit
          rm -rf build
          export CXX=clang++-18
          export CC=clang-18
          conan profile detect
      init: conan install . -pr:a conan_profiles/clang_debug_linux --build=missing
      command: cmake -S . -B build --preset=linux-clang-debug

vscode:
    extensions:
        - ms-vscode.cmake-tools
        - github.vscode-pull-request-github
        - jnoortheen.nix-ide
        - webfreak.debug
        - mhutchie.git-graph
        - gruntfuggly.todo-tree
        - vscode-icons-team.vscode-icons
        - matepek.vscode-catch2-test-adapter
        - xaver.clang-format
        - streetsidesoftware.code-spell-checker
