---
image:
    file: .gitpod.Dockerfile

tasks:
    - before: pip3 install --upgrade conan && pre-commit install -f --hook-type pre-commit
      init: cmake -S . --preset=linux-ninja-clang
      command: cmake --build -S . --preset=linux-clean-build


vscode:
    extensions:
        - ms-vscode.cmake-tools@1.6.0:lvoCR5usjseB5thI3sZhWA==
        - twxs.cmake@0.0.17:aQNzlYa74rJFJ5/BnUF1yA==
        - webfreak.debug@0.25.0:F9uLpAOde6r0l7rgMC8LTQ==
