---
image:
    file: .gitpod.Dockerfile

tasks:
    - init: pip3 install --upgrade conan && pre-commit install -f --hook-type pre-commit
      command: rm -rf ./build && cmake -S . --preset=linux-debug-ninja-clang

vscode:
    extensions:
        - ms-vscode.cmake-tools
        - twxs.cmake
        - github.vscode-pull-request-github
        - shd101wyy.markdown-preview-enhanced
        - jnoortheen.nix-ide
        - lextudio.restructuredtext
        - webfreak.debug
        - matepek.vscode-catch2-test-adapter
        - hbenl.vscode-test-explorer
        - mhutchie.git-graph
        - coenraads.bracket-pair-colorizer
        - gruntfuggly.todo-tree
        - vscode-icons-team.vscode-icons
