image:
  file: .gitpod.Dockerfile

tasks:
  - init: pip3 install --upgrade conan
    command: ./build.sh


vscode:
  extensions:
    - ms-vscode.cmake-tools@1.6.0:lvoCR5usjseB5thI3sZhWA==
    - twxs.cmake@0.0.17:aQNzlYa74rJFJ5/BnUF1yA==
    - webfreak.debug@0.25.0:F9uLpAOde6r0l7rgMC8LTQ==