---
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.4.0
      hooks:
          - id: check-added-large-files
          - id: check-byte-order-marker
          - id: check-case-conflict
          - id: check-merge-conflict
          - id: check-symlinks
          - id: check-yaml
          - id: check-json
          - id: check-toml
          - id: check-executables-have-shebangs
          - id: end-of-file-fixer
          - id: mixed-line-ending
          - id: trailing-whitespace
    - repo: https://github.com/pocc/pre-commit-hooks
      rev: v1.1.1
      hooks:
          - id: clang-format
            args: [--style=file, -i]
    - repo: https://github.com/iconmaster5326/cmake-format-pre-commit-hook
      rev: v0.6.5
      hooks:
          - id: cmake-format
    - repo: https://github.com/adrienverge/yamllint.git
      rev: v1.26.1
      hooks:
          - id: yamllint
            args: [--format, parsable, -d, relaxed]
    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.1.0
      hooks:
          - id: yamlfmt
