# versions
set(CPACK_PACKAGE_VERSION_MAJOR "${PROJECT_VERSION_MAJOR}")
set(CPACK_PACKAGE_VERSION_MINOR "${PROJECT_VERSION_MINOR}")
set(CPACK_PACKAGE_VERSION_PATCH "${PROJECT_VERSION_PATCH}")
set(CPACK_PACKAGE_VERSION
    "${CPACK_PACKAGE_VERSION_MAJOR}.${CPACK_PACKAGE_VERSION_MINOR}.${CPACK_PACKAGE_VERSION_PATCH}"
)

# general settings
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY
    "Present the current data of Corona (Covid-19) cases for a country."
)
set(CPACK_PACKAGE_DESCRIPTION_FILE "${PROJECT_SOURCE_DIR}/README.md")
set(CPACK_PACKAGE_VENDOR "Michel Estermann")
set(CPACK_PACKAGE_INSTALL_DIRECTORY
    "Cpp CMake Project Template ${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR}"
)

set(CPACK_RESOURCE_FILE_LICENSE "${PROJECT_SOURCE_DIR}/LICENSE")

# DEB package config
set(CPACK_DEBIAN_PACKAGE_NAME "coronan")
set(CPACK_PACKAGE_VENDOR "bbv Software Services AG")
set(CPACK_PACKAGE_CONTACT "michel.estermann@bbv.ch")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER
    "Michel Estermann <michel.estermann@bbv.ch>"
)
set(CPACK_DEBIAN_PACKAGE_HOMEPAGE "https://github.com/bbvch/Coronan")
set(CPACK_DEBIAN_PACKAGE_DEPENDS "libqt5widgets5,libQt5Charts5")

find_program(DPKG_PROGRAM dpkg)
if(DPKG_PROGRAM)
  list(APPEND CPACK_GENERATOR "DEB")
  set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS ON)
endif(DPKG_PROGRAM)

include(CPack)
