function(enable_doxygen)
    find_package(Doxygen OPTIONAL_COMPONENTS dot)
    if(Doxygen_FOUND)
        option(ENABLE_DOXYGEN "Enable doxygen doc builds of source" ON)
        if(ENABLE_DOXYGEN)
            set(DOXYGEN_CALLER_GRAPH YES)
            set(DOXYGEN_CALL_GRAPH YES)
            set(DOXYGEN_EXTRACT_ALL YES)
            set(DOXYGEN_GENERATE_TREEVIEW YES)
            set(DOXYGEN_BUILTIN_STL_SUPPORT YES)
            set(DOXYGEN_DOT_IMAGE_FORMAT svg)
            set(DOXYGEN_DOT_TRANSPARENT YES)
        endif()
    endif()
endfunction()
