---
name: Linux Sanatizer Builds

on:
    push:
    pull_request:
    release:
        types: [published]

jobs:
    ci:
        name: ${{ matrix.name }}
        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false
            matrix:
                include:
                    - name: ubuntu-22.04-clang-13-address
                      os: ubuntu-22.04
                      compiler: clang++-13
                      ccompiler: clang-13
                      clang-tidy: clang-tidy-13
                      generator: Ninja
                      profile: linux-clang-address-sanitizers
                    - name: ubuntu-22.04-clang-14-address
                      os: ubuntu-22.04
                      compiler: clang++-14
                      ccompiler: clang-14
                      clang-tidy: clang-tidy-14
                      generator: Ninja
                      profile: linux-clang-address-sanitizers
                    - name: ubuntu-22.04-clang-15-address
                      os: ubuntu-22.04
                      compiler: clang++-15
                      ccompiler: clang-15
                      clang-tidy: clang-tidy-15
                      generator: Ninja
                      profile: linux-clang-address-sanitizers
                    - name: ubuntu-24.04-clang-16-address
                      os: ubuntu-24.04
                      compiler: clang++-16
                      ccompiler: clang-16
                      clang-tidy: clang-tidy-16
                      generator: Ninja
                      profile: linux-clang-address-sanitizers
                    - name: ubuntu-24.04-clang-17-address
                      os: ubuntu-24.04
                      compiler: clang++-17
                      ccompiler: clang-17
                      clang-tidy: clang-tidy-17
                      generator: Ninja
                      profile: linux-clang-address-sanitizers
                    - name: ubuntu-24.04-clang-18-address
                      os: ubuntu-24.04
                      compiler: clang++-18
                      ccompiler: clang-18
                      clang-tidy: clang-tidy-18
                      generator: Ninja
                      profile: linux-clang-address-sanitizers
                    - name: ubuntu-latest-address
                      os: ubuntu-latest
                      compiler: g++
                      ccompiler: gcc
                      clang-tidy: clang-tidy
                      generator: Ninja
                      profile: linux-clang-address-sanitizers
                    - name: ubuntu-22.04-clang-13-memory
                      os: ubuntu-22.04
                      compiler: clang++-13
                      ccompiler: clang-13
                      clang-tidy: clang-tidy-13
                      generator: Ninja
                      profile: linux-clang-memory-sanitizers
                    - name: ubuntu-22.04-clang-14-memory
                      os: ubuntu-22.04
                      compiler: clang++-14
                      ccompiler: clang-14
                      clang-tidy: clang-tidy-14
                      generator: Ninja
                      profile: linux-clang-memory-sanitizers
                    - name: ubuntu-22.04-clang-15-memory
                      os: ubuntu-22.04
                      compiler: clang++-15
                      ccompiler: clang-15
                      clang-tidy: clang-tidy-15
                      generator: Ninja
                      profile: linux-clang-memory-sanitizers
                    - name: ubuntu-24.04-clang-16-memory
                      os: ubuntu-24.04
                      compiler: clang++-16
                      ccompiler: clang-16
                      clang-tidy: clang-tidy-16
                      generator: Ninja
                      profile: linux-clang-memory-sanitizers
                    - name: ubuntu-24.04-clang-17-memory
                      os: ubuntu-24.04
                      compiler: clang++-17
                      ccompiler: clang-17
                      clang-tidy: clang-tidy-17
                      generator: Ninja
                      profile: linux-clang-memory-sanitizers
                    - name: ubuntu-24.04-clang-18-memory
                      os: ubuntu-24.04
                      compiler: clang++-18
                      ccompiler: clang-18
                      clang-tidy: clang-tidy-18
                      generator: Ninja
                      profile: linux-clang-memory-sanitizers
                    - name: ubuntu-latest-memory
                      os: ubuntu-latest
                      compiler: g++
                      ccompiler: gcc
                      clang-tidy: clang-tidy
                      generator: Ninja
                      profile: linux-clang-memory-sanitizers

        env:
            CXX: ${{ matrix.compiler }}
            CC: ${{ matrix.ccompiler }}

        steps:
            - uses: actions/checkout@v4
            - name: Cache (Conan)
              uses: actions/cache@v4
              with:
                  path: ~/.conan2/p
                  key: cache-${{ matrix.os }}-${{ matrix.compiler }}-conan-${{ hashFiles('conanfile.txt') }}
                  restore-keys: |
                      cache-${{ matrix.os }}-${{ matrix.compiler }}-conan
            - name: Cache (ccache)
              uses: actions/cache@v4
              with:
                  path: |
                      ~/.cache/ccache
                  key: ccache-${{ matrix.os }}-${{ matrix.compiler }}-${{ matrix.generator }}-${{ hashFiles('**/CMakeLists.txt') }}
                  restore-keys: |
                      ccache-${{ matrix.os }}-${{ matrix.compiler }}
            - name: Install dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install -y --no-install-recommends ccache ninja-build ${{ matrix.clang-tidy }} dpkg pkg-config doxygen lcov
                  sudo apt-get install -y --no-install-recommends libgl1-mesa-dev freeglut3-dev
            - name: Install Qt
              run: |
                  sudo apt-get update
                  sudo apt-get install -y --no-install-recommends qt6-base-dev qt6-tools-dev qt6-tools-dev-tools libqt6charts6 libqt6charts6-dev libqt6opengl6 libqt6opengl6-dev '^libxcb.*-dev' libgles2-mesa-dev libx11-xcb-dev libgl1-mesa-dev libglu1-mesa-dev libxrender-dev libxi-dev libxkbcommon-dev libxkbcommon-x11-dev
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: 3.x
            - name: Install python dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r py-requirements.txt
            - name: Set conan compiler env
              run: conan profile detect
            - name: conan install
              run: conan install . --build=missing --settings=build_type=Debug --settings=compiler.cppstd=17
            - name: CMake configure
              run: |
                  cmake -S . --preset=${{ matrix.profile }}
            - name: CMake build
              run: cmake --build ./build
            - name: CTest
              run: ctest -C Debug
              working-directory: ./build
