---
name: MacOS Builds

on:
    push:
    pull_request:
    release:
        types: [published]

jobs:
    ci:
        name: ${{ matrix.name }}
        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false
            matrix:
                include:
                    - name: macos-10.15-clang
                      os: macos-10.15
                      build_type: Release
                      compiler: clang++
                      ccompiler: clang
                      generators: Unix Makefiles
                    - name: macos-11-clang
                      os: macos-11
                      build_type: Release
                      compiler: clang++
                      ccompiler: clang
                      generators: Unix Makefiles

        env:
            CXX: ${{ matrix.compiler }}
            CC: ${{ matrix.ccompiler }}

        steps:
            - uses: actions/checkout@v2
            - name: Install dependencies
              run: |
                  brew install ninja doxygen
            - name: Python pip Cache
              uses: actions/cache@v2
              with:
                  path: ~/Library/Caches/pip
                  key: pip-${{ matrix.name }}-${{ hashFiles('py-requirements.txt') }}
            - name: Install python dependencies
              run: |
                  python3 -m pip install --upgrade pip
                  python3 -m pip install -r py-requirements.txt
            - name: Install Qt
              uses: jurplel/install-qt-action@v2
              with:
                  version: 5.15.2
                  host: mac
                  target: desktop
                  modules: qtcharts
                  tools: tools_ifw,4.0,qt.tools.ifw.40
            - name: Conan Cache
              uses: actions/cache@v2
              with:
                  path: ~/.conan/data
                  key: conan-${{ matrix.name }}-${{ hashFiles('**/Conan.cmake') }}
            - name: Create build dir
              run: mkdir build
            - name: CMake configure
              run: cmake -S . -B ./build -G "${{ matrix.generators }}" -DENABLE_COVERAGE=${{ matrix.coverage }} -DCMAKE_BUILD_TYPE=${{ matrix.build_type
                  }}
            - name: CMake build
              run: cmake --build ./build --config ${{ matrix.build_type }}
            - name: CTest
              run: ctest -C Debug
              working-directory: ./build
            - name: CMake build docs
              run: cmake --build ./build --target docs --config ${{ matrix.build_type }}
            - name: CMake build package
              run: cmake --build ./build --target package --config ${{ matrix.build_type }}
            - uses: actions/upload-artifact@v2
              with:
                  name: ${{ matrix.name }}-artifacts
                  path: |
                      ./build/Coronan-*.tar.gz
                      ./build/Coronan-*.pkg
