---
name: Coverity Scan

on:
    push:
        branches: [master]


jobs:
    coverity:
        runs-on: ubuntu-20.04
        env:
            CXX: g++
            CC: gcc
        steps:
            - uses: actions/checkout@v2
            - name: Install dependencies (Linux)
              if: runner.os == 'Linux'
              run: |
                  sudo apt-get update
                  sudo apt-get install -y --no-install-recommends ninja-build python3-pip python3-setuptools libqt5charts5-dev libglib2.0-dev
                  sudo apt-get install -y --no-install-recommends dpkg pkg-config doxygen
            - name: Install python dependencies
              run: |
                  python3 -m pip install conan
                  conan --version
            - name: Set conan compiler env (gcc)
              run: |
                  conan profile new default --detect
                  conan profile update settings.compiler.libcxx=libstdc++11 default
            - name: Create build dir
              run: mkdir build
            - name: CMake configure
              run: cmake -S . -B ./build -G "Ninja" -DCMAKE_BUILD_TYPE=Debug
            - uses: vapier/coverity-scan-action@v0
              with:
                  project: bbvch%2FCoronan
                  token: ${{ secrets.COVERITY_SCAN_TOKEN }}
                  email: estermann.michel@gmail.com
                  build_language: cxx
                  command: cmake --build ./build
