---
name: Nix Builds

on:
    push:
    pull_request:
    release:
        types: [published]
jobs:
    nix_build:
        name: ${{ matrix.name }}
        runs-on: ubuntu-20.04

        strategy:
            fail-fast: false
            matrix:
                include:
                    - name: nix-gcc
                      configure_preset: linux-debug-ninja
                      build_preset: ninja-debug
                      CONAN_USER_HOME: ~/.conan
                    - name: nix-clang
                      configure_preset: linux-debug-ninja-clang
                      build_preset: clang-debug
                      CONAN_USER_HOME: ~/.conan-clang
        steps:
            - uses: actions/checkout@v4
            - name: Cache (Conan)
              uses: actions/cache@v4
              with:
                  path: ~/.conan/data
                  key: cache-${{ matrix.name }}-conan-${{ hashFiles('**/Conan.cmake') }}
            - uses: cachix/install-nix-action@v27
              with:
                  nix_path: nixpkgs=channel:nixos-24.11
            - uses: cachix/cachix-action@v15
              with:
                  name: bbvch
                  authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
            - run: |
                  nix-shell --command "conan profile detect"
                  nix-shell --command "conan install . --build=missing --settings=build_type=Debug"
                  nix-shell --command "cmake -S ${GITHUB_WORKSPACE} --preset=${{ matrix.configure_preset }}"
                  nix-shell --command "cmake --build --preset=${{ matrix.build_preset }}"
