---
name: Nix Builds

on:
    push:
    pull_request:
    release:
        types: [published]
jobs:
    nix_build:
        name: ${{ matrix.name }}
        runs-on: ubuntu-24.04

        strategy:
            fail-fast: false
            matrix:
                include:
                    - name: nix-gcc
                      configure_preset: linux-gcc-debug
                      build_preset: gcc-debug
                      CONAN_USER_HOME: ~/.conan2
                    - name: nix-clang
                      configure_preset: linux-clang-debug
                      build_preset: clang-debug
                      CONAN_USER_HOME: ~/.conan2
        steps:
            - uses: actions/checkout@v4
            - name: Cache (Conan)
              uses: actions/cache@v4
              with:
                  path: ~/.conan2/p
                  key: cache-${{ matrix.name }}-conan-${{ hashFiles('conanfile.txt') }}
            - uses: cachix/install-nix-action@v27
              with:
                  nix_path: nixpkgs=channel:nixos-24.11
            - uses: cachix/cachix-action@v15
              with:
                  name: bbvch
                  authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
            - run: |
                  nix-shell --command "conan profile detect"
                  nix-shell --command "conan install . --build=missing --settings=build_type=Debug"
                  nix-shell --command "cmake -S ${GITHUB_WORKSPACE} --preset=${{ matrix.configure_preset }}"
                  nix-shell --command "cmake --build --preset=${{ matrix.build_preset }}"
